export type Language =
  | "C"
  | "C++"
  | "CSS"
  | "Dart"
  | "Elixir"
  | "Go"
  | "Haskell"
  | "HTML"
  | "Java"
  | "JavaScript"
  | "JSON"
  | "Jupyter Notebook"
  | "Kotlin"
  | "Lean"
  | "Makefile"
  | "Markdown"
  | "Python"
  | "Ruby"
  | "Rust"
  | "Shell"
  | "Swift"
  | "TypeScript"
  | "YAML"

export type Category =
  "CLI" | "GitHub Action" | "Library" | "Template" | "Experiment"

export type SectionCategory =
  "CLI" | "GitHub" | "Libraries" | "Templates" | "Experiments"

export type Project = {
  name: string
  slug: string
  description: string
  language: Language
  category: Category
  github: string
  overview: string
  installation: string
  license: string
  status: "Stable" | "Experimental"
  related: string[]
}

export function getProject(slug: string): Project | undefined {
  return projects.find((project) => project.slug === slug)
}

export const languages: Language[] = [
  "C",
  "C++",
  "CSS",
  "Dart",
  "Elixir",
  "Go",
  "Haskell",
  "HTML",
  "Java",
  "JavaScript",
  "JSON",
  "Jupyter Notebook",
  "Kotlin",
  "Lean",
  "Makefile",
  "Markdown",
  "Python",
  "Ruby",
  "Rust",
  "Shell",
  "Swift",
  "TypeScript",
  "YAML",
]

export const categories: {
  name: SectionCategory
  blurb: string
  count: number
}[] = [
  {
    name: "CLI",
    blurb: "Developer utilities for everyday workflows.",
    count: 31,
  },
  {
    name: "GitHub",
    blurb: "Actions, reusable workflows, and automation.",
    count: 33,
  },
  {
    name: "Libraries",
    blurb: "Reusable building blocks.",
    count: 21,
  },
  {
    name: "Templates",
    blurb: "Project starters and boilerplates.",
    count: 15,
  },
  {
    name: "Experiments",
    blurb: "Ideas that may eventually become tools.",
    count: 44,
  },
]

export const projects: Project[] = [
  {
    name: "clipb",
    slug: "clipb",
    description: "A lightweight clipboard utility for developers.",
    language: "Rust",
    category: "CLI",
    github: "https://github.com/coccinella-labs/clipb",
    overview:
      "clipb copies file paths to the system clipboard without leaving your terminal. It prints the copied paths back to stdout so you can chain it into other commands, and it handles spaces, symlinks, and relative paths correctly. No wrappers, no daemons, no bloat.",
    installation: "cargo install --git https://github.com/coccinella-labs/clipb",
    license: "MIT",
    status: "Stable",
    related: ["dotenv-keep", "craft"],
  },
  {
    name: "craft",
    slug: "craft",
    description: "Experimental Rust developer tool.",
    language: "Rust",
    category: "Experiment",
    github: "https://github.com/coccinella-labs/craft",
    overview:
      "craft explores installing tools as single, signed binaries without package-manager lock-in. It is an experiment: the interface may change, and the philosophy is being tested. Try it, break it, and tell us what you find.",
    installation: "cargo install --git https://github.com/coccinella-labs/craft",
    license: "MIT",
    status: "Experimental",
    related: ["clipb"],
  },
  {
    name: "dotenv-keep",
    slug: "dotenv-keep",
    description: "Keep and manage .env files safely.",
    language: "Python",
    category: "CLI",
    github: "https://github.com/coccinella-labs/dotenv-keep",
    overview:
      "dotenv-keep compares your .env.example against the variables referenced in your code and reports names that are missing, unused, or drifted. It catches the silent misconfig that only shows up in production.",
    installation: "pip install git+https://github.com/coccinella-labs/dotenv-keep",
    license: "MIT",
    status: "Stable",
    related: ["clipb"],
  },
  {
    name: "mini",
    slug: "mini",
    description: "A minimal Go utility library.",
    language: "Go",
    category: "Library",
    github: "https://github.com/coccinella-labs/mini",
    overview:
      "mini is a single-file HTTP client with no third-party dependencies. It keeps memory use small enough for embedded runtimes, exposes a straightforward request/response API, and can be vendored directly into any project.",
    installation: "go get github.com/coccinella-labs/mini@latest",
    license: "MIT",
    status: "Stable",
    related: ["startkit"],
  },
  {
    name: "startkit",
    slug: "startkit",
    description: "Minimal project template for new libraries.",
    language: "JavaScript",
    category: "Template",
    github: "https://github.com/coccinella-labs/startkit",
    overview:
      "startkit gives you a publish-ready library with nothing beyond the essentials: a test runner, a linter, and a release script. Run it, rename it, and ship. It follows the coccinella-labs principles by making the small choices for you.",
    installation: "npx --yes github:coccinella-labs/startkit mylib",
    license: "MIT",
    status: "Stable",
    related: ["mini"],
  },
  {
    name: "release-notes",
    slug: "release-notes",
    description: "GitHub Action for generating release notes.",
    language: "TypeScript",
    category: "GitHub Action",
    github: "https://github.com/coccinella-labs/release-notes",
    overview:
      "release-notes reads the commits merged between two tags, groups them by conventional-commit type, and writes a markdown file you can attach to a GitHub release. It keeps the changelog honest without a dedicated changelog tool in the repo.",
    installation: "- uses: coccinella-labs/release-notes@main",
    license: "MIT",
    status: "Stable",
    related: ["gh-tag"],
  },
  {
    name: "fmtcheck",
    slug: "fmtcheck",
    description: "GitHub Action for formatting checks.",
    language: "Go",
    category: "GitHub Action",
    github: "https://github.com/coccinella-labs/fmtcheck",
    overview:
      "fmtcheck runs your language's canonical formatter in check mode and fails the build on any diff. Formatting debates stay out of code review because the machine settles them in CI. Zero configuration for the common case.",
    installation: "- uses: coccinella-labs/fmtcheck@main",
    license: "MIT",
    status: "Stable",
    related: ["release-notes", "rust-fix"],
  },
  {
    name: "gh-tag",
    slug: "gh-tag",
    description: "GitHub Action for automated version tagging.",
    language: "TypeScript",
    category: "GitHub Action",
    github: "https://github.com/coccinella-labs/gh-tag",
    overview:
      "gh-tag checks whether a tag already exists, creates it as an annotated semver tag pointing at the current commit, and reports whether it was created. It pairs with release-notes to turn a push into a fully tagged release.",
    installation: "- uses: coccinella-labs/gh-tag@main",
    license: "MIT",
    status: "Stable",
    related: ["release-notes", "release"],
  },
  {
    name: "release",
    slug: "release",
    description: "Runs release automation.",
    language: "Shell",
    category: "GitHub Action",
    github: "https://github.com/coccinella-labs/release",
    overview:
      "An automated release workflow for multi-package repositories. release analyzes commits since the last release tag, determines the version bump type (major, minor, or patch), and can create a release PR, commit and tag directly, or wait for a merge before tagging.",
    installation: "- uses: coccinella-labs/release@v1.0.0",
    license: "MIT",
    status: "Stable",
    related: ["bump", "gh-tag"],
  },
  {
    name: "stale",
    slug: "stale",
    description: "Closes stale issues.",
    language: "Shell",
    category: "GitHub Action",
    github: "https://github.com/coccinella-labs/stale",
    overview:
      "A reusable action that closes stale issues after a period of inactivity, so the issue list stays honest and current.",
    installation: "- uses: coccinella-labs/stale@v1",
    license: "MIT",
    status: "Stable",
    related: [],
  },
  {
    name: "auto-merge",
    slug: "auto-merge",
    description: "Merges pull requests automatically.",
    language: "Shell",
    category: "GitHub Action",
    github: "https://github.com/coccinella-labs/auto-merge",
    overview:
      "Enables or disables auto-merge on pull requests. It can wait for checks to pass, cancel auto-merge, or merge immediately.",
    installation: "- uses: coccinella-labs/auto-merge@v1",
    license: "MIT",
    status: "Stable",
    related: ["lock"],
  },
  {
    name: "title",
    slug: "title",
    description: "Fixes pull request titles.",
    language: "Shell",
    category: "GitHub Action",
    github: "https://github.com/coccinella-labs/title",
    overview:
      "Rewrites pull request titles into a conventional format, so commit history and changelogs line up without hand-editing.",
    installation: "- uses: coccinella-labs/title@v1",
    license: "MIT",
    status: "Stable",
    related: ["prune"],
  },
  {
    name: "cancel",
    slug: "cancel",
    description: "Cancels workflow runs.",
    language: "Shell",
    category: "GitHub Action",
    github: "https://github.com/coccinella-labs/cancel",
    overview:
      "Cancels in-progress and queued workflow runs for a branch, so superseded CI stops wasting runner time.",
    installation: "- uses: coccinella-labs/cancel@v1",
    license: "MIT",
    status: "Stable",
    related: [],
  },
  {
    name: "lock",
    slug: "lock",
    description: "Locks merged pull requests.",
    language: "Shell",
    category: "GitHub Action",
    github: "https://github.com/coccinella-labs/lock",
    overview:
      "Locks merged pull requests after a configurable delay, keeping conversation concentrated on open work.",
    installation: "- uses: coccinella-labs/lock@v1",
    license: "MIT",
    status: "Stable",
    related: ["stale"],
  },
  {
    name: "auto-label",
    slug: "auto-label",
    description: "Labels issues and pull requests.",
    language: "Shell",
    category: "GitHub Action",
    github: "https://github.com/coccinella-labs/auto-label",
    overview:
      "Labels issues and pull requests automatically based on commits, changed files, and the shape of the change.",
    installation: "- uses: coccinella-labs/auto-label@v2",
    license: "MIT",
    status: "Stable",
    related: ["title"],
  },
  {
    name: "prune",
    slug: "prune",
    description: "Normalizes pull request descriptions.",
    language: "Shell",
    category: "GitHub Action",
    github: "https://github.com/coccinella-labs/prune",
    overview:
      "Writes a pull request description from the actual diff, so reviewers always have an accurate summary of what changed.",
    installation: "- uses: coccinella-labs/prune@v1",
    license: "MIT",
    status: "Stable",
    related: ["title"],
  },
  {
    name: "rust-fix",
    slug: "rust-fix",
    description: "Applies Rust code fixes.",
    language: "Rust",
    category: "GitHub Action",
    github: "https://github.com/coccinella-labs/rust-fix",
    overview:
      "Auto-fixes Rust code with cargo fmt and clippy and opens a fix as a pull request, keeping the formatting debate out of review.",
    installation: "- uses: coccinella-labs/rust-fix@v1",
    license: "MIT",
    status: "Stable",
    related: ["fmtcheck"],
  },
  {
    name: "bump",
    slug: "bump",
    description: "Automates version bumps.",
    language: "Shell",
    category: "GitHub Action",
    github: "https://github.com/coccinella-labs/bump",
    overview:
      "Orchestrates version bumps after merged pull requests, handling the version-bump PR, tagging, and release flow as one reusable action.",
    installation: "- uses: coccinella-labs/bump@main",
    license: "MIT",
    status: "Stable",
    related: ["release", "gh-tag"],
  },
  {
    name: "echo",
    slug: "echo",
    description: "Suggests related issues.",
    language: "Python",
    category: "GitHub Action",
    github: "https://github.com/coccinella-labs/echo",
    overview:
      "Suggests potentially similar existing issues and posts a triage comment, so duplicates are spotted before the queue grows.",
    installation: "- uses: coccinella-labs/echo@main",
    license: "MIT",
    status: "Stable",
    related: ["auto-label"],
  },
  {
    name: "gon",
    slug: "gon",
    description: "Reviews Dependabot pull requests.",
    language: "Python",
    category: "GitHub Action",
    github: "https://github.com/coccinella-labs/gon",
    overview:
      "A calm reusable workflow that gently reviews Dependabot pull requests and provides clear summaries to help you merge confidently.",
    installation: "- uses: coccinella-labs/gon/.github/workflows/gon.yml@main",
    license: "MIT",
    status: "Stable",
    related: ["auto-merge"],
  },
  {
    name: "nightly",
    slug: "nightly",
    description: "Builds Flutter desktop nightlies.",
    language: "YAML",
    category: "GitHub Action",
    github: "https://github.com/coccinella-labs/nightly",
    overview:
      "A reusable workflow that builds Flutter desktop apps overnight, only when there are new commits since the last nightly, and tags each build with a dated tag.",
    installation: "- uses: coccinella-labs/nightly/.github/workflows/nightly.yml@main",
    license: "MIT",
    status: "Stable",
    related: [],
  },
  {
    name: "rust-nightly",
    slug: "rust-nightly",
    description: "Builds Rust nightlies.",
    language: "YAML",
    category: "GitHub Action",
    github: "https://github.com/coccinella-labs/rust-nightly",
    overview:
      "A reusable nightly workflow for Rust projects: runs the full test suite with all features, builds in release mode, and can upload coverage.",
    installation: "- uses: coccinella-labs/rust-nightly/.github/workflows/nightly.yml@main",
    license: "MIT",
    status: "Stable",
    related: ["fmtcheck"],
  },
  {
    name: "release-assets",
    slug: "release-assets",
    description: "Builds signed release assets.",
    language: "Python",
    category: "GitHub Action",
    github: "https://github.com/coccinella-labs/release-assets",
    overview:
      "A reusable workflow that builds, packages, signs, smoke-tests, and publishes release assets for CLI tools across a platform matrix.",
    installation: "- uses: coccinella-labs/release-assets/.github/workflows/release-assets.yml@main",
    license: "MIT",
    status: "Stable",
    related: ["release", "rust-fix"],
  },
  {
    name: "activity",
    slug: "activity",
    description: "Tracks project activity.",
    language: "YAML",
    category: "GitHub Action",
    github: "https://github.com/coccinella-labs/activity",
    overview:
      "A reusable workflow that tracks project activity in a central issue, giving a single place to see what moved across a repository.",
    installation: "- uses: coccinella-labs/activity/.github/workflows/tracking.yml@main",
    license: "MIT",
    status: "Stable",
    related: [],
  },
  {
    name: "bot",
    slug: "bot",
    description: "Bot identity for automation.",
    language: "Python",
    category: "GitHub Action",
    github: "https://github.com/coccinella-labs/bot",
    overview:
      "A programmable GitHub bot used for automated commits. It provides an action that commits changes under a dedicated bot identity with a stable avatar.",
    installation: "- uses: coccinella-labs/bot/actions/commit@v1",
    license: "MIT",
    status: "Stable",
    related: ["prune", "rust-fix"],
  },
  {
    name: 'agentware',
    slug: 'agentware',
    description: 'AI-assisted coding tools and developer workflows.',
    language: 'C++',
    category: 'CLI',
    github: 'https://github.com/coccinella-labs/agentware',
    overview: 'AI-assisted coding tools and developer workflows. It stays small enough to read and replace.',
    installation: 'git clone https://github.com/coccinella-labs/agentware',
    license: 'Apache-2.0',
    status: 'Stable',
    related: [],
  },
  {
    name: 'ai',
    slug: 'ai',
    description: 'AI notes.',
    language: 'Python',
    category: 'Experiment',
    github: 'https://github.com/coccinella-labs/ai',
    overview: 'AI notes. Expect rough edges while its shape is being tested.',
    installation: 'pip install git+https://github.com/coccinella-labs/ai',
    license: 'MIT',
    status: 'Experimental',
    related: [],
  },
  {
    name: 'and',
    slug: 'and',
    description: 'Short notes.',
    language: 'Python',
    category: 'Experiment',
    github: 'https://github.com/coccinella-labs/and',
    overview: 'Short notes. Expect rough edges while its shape is being tested.',
    installation: 'pip install git+https://github.com/coccinella-labs/and',
    license: 'MIT',
    status: 'Experimental',
    related: [],
  },
  {
    name: 'applekernel',
    slug: 'applekernel',
    description: 'Apple silicon kernel notes.',
    language: 'Swift',
    category: 'Experiment',
    github: 'https://github.com/coccinella-labs/applekernel',
    overview: 'Apple silicon kernel notes. Expect rough edges while its shape is being tested.',
    installation: 'git clone https://github.com/coccinella-labs/applekernel',
    license: 'MIT',
    status: 'Experimental',
    related: [],
  },
  {
    name: 'appsdk',
    slug: 'appsdk',
    description: 'GitHub App framework.',
    language: 'JavaScript',
    category: 'Library',
    github: 'https://github.com/coccinella-labs/appsdk',
    overview: 'GitHub App framework. It works on its own, without tying you down.',
    installation: 'npm install github:coccinella-labs/appsdk',
    license: 'MIT',
    status: 'Stable',
    related: [],
  },
  {
    name: 'barepi',
    slug: 'barepi',
    description: 'Raspberry Pi notes.',
    language: 'C',
    category: 'Experiment',
    github: 'https://github.com/coccinella-labs/barepi',
    overview: 'Raspberry Pi notes. Expect rough edges while its shape is being tested.',
    installation: 'git clone https://github.com/coccinella-labs/barepi',
    license: 'BSD-3-Clause',
    status: 'Experimental',
    related: [],
  },
  {
    name: 'benchmark',
    slug: 'benchmark',
    description: 'Speech benchmark.',
    language: 'Python',
    category: 'Experiment',
    github: 'https://github.com/coccinella-labs/benchmark',
    overview: 'Speech benchmark. Expect rough edges while its shape is being tested.',
    installation: 'pip install git+https://github.com/coccinella-labs/benchmark',
    license: 'MIT',
    status: 'Experimental',
    related: [],
  },
  {
    name: 'bible',
    slug: 'bible',
    description: 'Bible notes.',
    language: 'Markdown',
    category: 'Experiment',
    github: 'https://github.com/coccinella-labs/bible',
    overview: 'Bible notes. Expect rough edges while its shape is being tested.',
    installation: 'git clone https://github.com/coccinella-labs/bible',
    license: 'MIT',
    status: 'Experimental',
    related: [],
  },
  {
    name: 'bin',
    slug: 'bin',
    description: 'Elixir pipeline.',
    language: 'Elixir',
    category: 'Library',
    github: 'https://github.com/coccinella-labs/bin',
    overview: 'Elixir pipeline. It works on its own, without tying you down.',
    installation: 'git clone https://github.com/coccinella-labs/bin',
    license: 'Apache-2.0',
    status: 'Stable',
    related: [],
  },
  {
    name: 'bitinfer',
    slug: 'bitinfer',
    description: 'Inference framework.',
    language: 'C++',
    category: 'Library',
    github: 'https://github.com/coccinella-labs/bitinfer',
    overview: 'Inference framework. It works on its own, without tying you down.',
    installation: 'git clone https://github.com/coccinella-labs/bitinfer',
    license: 'MIT',
    status: 'Stable',
    related: [],
  },
  {
    name: 'bniladridas',
    slug: 'bniladridas',
    description: 'Profile open.',
    language: 'Markdown',
    category: 'Experiment',
    github: 'https://github.com/coccinella-labs/bniladridas',
    overview: 'Profile open. Expect rough edges while its shape is being tested.',
    installation: 'git clone https://github.com/coccinella-labs/bniladridas',
    license: 'MIT',
    status: 'Experimental',
    related: [],
  },
  {
    name: 'bniladridas-profile',
    slug: 'bniladridas-profile',
    description: 'Profile resources.',
    language: 'Shell',
    category: 'Template',
    github: 'https://github.com/coccinella-labs/bniladridas-profile',
    overview: 'Profile resources. The scaffolding is minimal, so the real work is yours.',
    installation: 'git clone https://github.com/coccinella-labs/bniladridas-profile',
    license: 'MIT',
    status: 'Stable',
    related: [],
  },
  {
    name: 'bot-identity',
    slug: 'bot-identity',
    description: 'Bot identity for automation.',
    language: 'Shell',
    category: 'GitHub Action',
    github: 'https://github.com/coccinella-labs/bot-identity',
    overview: 'Bot identity for automation. It slots into a workflow with a single use.',
    installation: '- uses: coccinella-labs/bot-identity@main',
    license: 'MIT',
    status: 'Stable',
    related: [],
  },
  {
    name: 'brew',
    slug: 'brew',
    description: 'Firmware baseline.',
    language: 'C',
    category: 'Experiment',
    github: 'https://github.com/coccinella-labs/brew',
    overview: 'Firmware baseline. Expect rough edges while its shape is being tested.',
    installation: 'git clone https://github.com/coccinella-labs/brew',
    license: 'MIT',
    status: 'Experimental',
    related: [],
  },
  {
    name: 'browser',
    slug: 'browser',
    description: 'Flutter browser app.',
    language: 'Dart',
    category: 'Experiment',
    github: 'https://github.com/coccinella-labs/browser',
    overview: 'Flutter browser app. Expect rough edges while its shape is being tested.',
    installation: 'git clone https://github.com/coccinella-labs/browser',
    license: 'MIT',
    status: 'Experimental',
    related: [],
  },
  {
    name: 'browser-archive',
    slug: 'browser-archive',
    description: 'Archived browser app.',
    language: 'Dart',
    category: 'Experiment',
    github: 'https://github.com/coccinella-labs/browser-archive',
    overview: 'Archived browser app. Expect rough edges while its shape is being tested.',
    installation: 'git clone https://github.com/coccinella-labs/browser-archive',
    license: 'MIT',
    status: 'Experimental',
    related: [],
  },
  {
    name: 'buildanywhere',
    slug: 'buildanywhere',
    description: 'CI pipeline.',
    language: 'Shell',
    category: 'GitHub Action',
    github: 'https://github.com/coccinella-labs/buildanywhere',
    overview: 'CI pipeline. It slots into a workflow with a single use.',
    installation: '- uses: coccinella-labs/buildanywhere@main',
    license: 'MIT',
    status: 'Stable',
    related: [],
  },
  {
    name: 'calculator',
    slug: 'calculator',
    description: 'GTK calculator.',
    language: 'Haskell',
    category: 'Experiment',
    github: 'https://github.com/coccinella-labs/calculator',
    overview: 'GTK calculator. Expect rough edges while its shape is being tested.',
    installation: 'git clone https://github.com/coccinella-labs/calculator',
    license: 'MIT',
    status: 'Experimental',
    related: [],
  },
  {
    name: 'clabot',
    slug: 'clabot',
    description: 'CLA workflow.',
    language: 'JavaScript',
    category: 'GitHub Action',
    github: 'https://github.com/coccinella-labs/clabot',
    overview: 'CLA workflow. It slots into a workflow with a single use.',
    installation: '- uses: coccinella-labs/clabot@main',
    license: 'MIT',
    status: 'Stable',
    related: [],
  },
  {
    name: 'cli',
    slug: 'cli',
    description: 'Master CLI to control all repos.',
    language: 'Shell',
    category: 'CLI',
    github: 'https://github.com/coccinella-labs/cli',
    overview: 'Master CLI to control all repos. It stays small enough to read and replace.',
    installation: 'git clone https://github.com/coccinella-labs/cli',
    license: 'MIT',
    status: 'Stable',
    related: [],
  },
  {
    name: 'cli-tools',
    slug: 'cli-tools',
    description: 'CLI tools.',
    language: 'C++',
    category: 'CLI',
    github: 'https://github.com/coccinella-labs/cli-tools',
    overview: 'CLI tools. It stays small enough to read and replace.',
    installation: 'git clone https://github.com/coccinella-labs/cli-tools',
    license: 'MIT',
    status: 'Stable',
    related: [],
  },
  {
    name: 'clicompare',
    slug: 'clicompare',
    description: 'CLI comparison notes.',
    language: 'JavaScript',
    category: 'Experiment',
    github: 'https://github.com/coccinella-labs/clicompare',
    overview: 'CLI comparison notes. Expect rough edges while its shape is being tested.',
    installation: 'git clone https://github.com/coccinella-labs/clicompare',
    license: 'CC0-1.0',
    status: 'Experimental',
    related: [],
  },
  {
    name: 'collab-hub',
    slug: 'collab-hub',
    description: 'Collaboration app.',
    language: 'JavaScript',
    category: 'Experiment',
    github: 'https://github.com/coccinella-labs/collab-hub',
    overview: 'Collaboration app. Expect rough edges while its shape is being tested.',
    installation: 'git clone https://github.com/coccinella-labs/collab-hub',
    license: 'MIT',
    status: 'Experimental',
    related: [],
  },
  {
    name: 'commitfix',
    slug: 'commitfix',
    description: 'Commit message test.',
    language: 'Markdown',
    category: 'Experiment',
    github: 'https://github.com/coccinella-labs/commitfix',
    overview: 'Commit message test. Expect rough edges while its shape is being tested.',
    installation: 'git clone https://github.com/coccinella-labs/commitfix',
    license: 'MIT',
    status: 'Experimental',
    related: [],
  },
  {
    name: 'config',
    slug: 'config',
    description: 'GitHub CLI extension to manage warning messages from warnings repo.',
    language: 'Shell',
    category: 'CLI',
    github: 'https://github.com/coccinella-labs/config',
    overview: 'GitHub CLI extension to manage warning messages from the warnings repo. It stays small enough to read and replace.',
    installation: 'git clone https://github.com/coccinella-labs/config',
    license: 'MIT',
    status: 'Stable',
    related: [],
  },
  {
    name: 'core',
    slug: 'core',
    description: 'Metal-based GPU compute runtime focused on memory, synchronization, and data movement on Apple Silicon.',
    language: 'Swift',
    category: 'Library',
    github: 'https://github.com/coccinella-labs/core',
    overview: 'Metal-based GPU compute runtime focused on memory, synchronization, and data movement on Apple Silicon. It works on its own, without tying you down.',
    installation: 'git clone https://github.com/coccinella-labs/core',
    license: 'MIT',
    status: 'Stable',
    related: [],
  },
  {
    name: 'course',
    slug: 'course',
    description: 'Mac process orchestrator.',
    language: 'Swift',
    category: 'Library',
    github: 'https://github.com/coccinella-labs/course',
    overview: 'Mac process orchestrator. It works on its own, without tying you down.',
    installation: 'git clone https://github.com/coccinella-labs/course',
    license: 'MIT',
    status: 'Stable',
    related: [],
  },
  {
    name: 'dependabot-review',
    slug: 'dependabot-review',
    description: 'Dependabot review action.',
    language: 'YAML',
    category: 'GitHub Action',
    github: 'https://github.com/coccinella-labs/dependabot-review',
    overview: 'Dependabot review action. It slots into a workflow with a single use.',
    installation: '- uses: coccinella-labs/dependabot-review@main',
    license: 'MIT',
    status: 'Stable',
    related: [],
  },
  {
    name: 'diff',
    slug: 'diff',
    description: 'diff tool.',
    language: 'TypeScript',
    category: 'CLI',
    github: 'https://github.com/coccinella-labs/diff',
    overview: 'diff tool. It stays small enough to read and replace.',
    installation: 'git clone https://github.com/coccinella-labs/diff',
    license: 'MIT',
    status: 'Stable',
    related: [],
  },
  {
    name: 'diff-android',
    slug: 'diff-android',
    description: 'android diff app.',
    language: 'Kotlin',
    category: 'Experiment',
    github: 'https://github.com/coccinella-labs/diff-android',
    overview: 'android diff app. Expect rough edges while its shape is being tested.',
    installation: 'git clone https://github.com/coccinella-labs/diff-android',
    license: 'Apache-2.0',
    status: 'Experimental',
    related: [],
  },
  {
    name: 'diff-mac',
    slug: 'diff-mac',
    description: 'macos diff app.',
    language: 'Swift',
    category: 'Experiment',
    github: 'https://github.com/coccinella-labs/diff-mac',
    overview: 'macos diff app. Expect rough edges while its shape is being tested.',
    installation: 'git clone https://github.com/coccinella-labs/diff-mac',
    license: 'MIT',
    status: 'Experimental',
    related: [],
  },
  {
    name: 'dot',
    slug: 'dot',
    description: 'Dotnet notes.',
    language: 'CSS',
    category: 'Experiment',
    github: 'https://github.com/coccinella-labs/dot',
    overview: 'Dotnet notes. Expect rough edges while its shape is being tested.',
    installation: 'git clone https://github.com/coccinella-labs/dot',
    license: 'MIT',
    status: 'Experimental',
    related: [],
  },
  {
    name: 'dotfiles',
    slug: 'dotfiles',
    description: 'Dotfiles for Mac.',
    language: 'Shell',
    category: 'Template',
    github: 'https://github.com/coccinella-labs/dotfiles',
    overview: 'Dotfiles for Mac. The scaffolding is minimal, so the real work is yours.',
    installation: 'git clone https://github.com/coccinella-labs/dotfiles',
    license: 'MIT',
    status: 'Stable',
    related: [],
  },
  {
    name: 'fix',
    slug: 'fix',
    description: 'Commit message app.',
    language: 'Python',
    category: 'CLI',
    github: 'https://github.com/coccinella-labs/fix',
    overview: 'Commit message app. It stays small enough to read and replace.',
    installation: 'pip install git+https://github.com/coccinella-labs/fix',
    license: 'MIT',
    status: 'Stable',
    related: [],
  },
  {
    name: 'forkcheck',
    slug: 'forkcheck',
    description: 'Fork testing.',
    language: 'YAML',
    category: 'GitHub Action',
    github: 'https://github.com/coccinella-labs/forkcheck',
    overview: 'Fork testing. It slots into a workflow with a single use.',
    installation: '- uses: coccinella-labs/forkcheck@main',
    license: 'MIT',
    status: 'Stable',
    related: [],
  },
  {
    name: 'general',
    slug: 'general',
    description: 'A curated visual experience powered by Pexels API.',
    language: 'TypeScript',
    category: 'Experiment',
    github: 'https://github.com/coccinella-labs/general',
    overview: 'A curated visual experience powered by Pexels API. Expect rough edges while its shape is being tested.',
    installation: 'git clone https://github.com/coccinella-labs/general',
    license: 'MIT',
    status: 'Experimental',
    related: [],
  },
  {
    name: 'gradledemo',
    slug: 'gradledemo',
    description: 'Java HTTP demo.',
    language: 'Java',
    category: 'Experiment',
    github: 'https://github.com/coccinella-labs/gradledemo',
    overview: 'Java HTTP demo. Expect rough edges while its shape is being tested.',
    installation: 'git clone https://github.com/coccinella-labs/gradledemo',
    license: 'Unlicense',
    status: 'Experimental',
    related: [],
  },
  {
    name: 'gh-pin-repo',
    slug: 'gh-pin-repo',
    description: 'GitHub CLI extension to pin repositories.',
    language: 'Shell',
    category: 'CLI',
    github: 'https://github.com/coccinella-labs/gh-pin-repo',
    overview: 'GitHub CLI extension to pin repositories. It stays small enough to read and replace.',
    installation: 'git clone https://github.com/coccinella-labs/gh-pin-repo',
    license: 'MIT',
    status: 'Stable',
    related: [],
  },
  {
    name: 'gitkeep',
    slug: 'gitkeep',
    description: 'Empty template repo with .gitkeep for meta purposes.',
    language: 'Markdown',
    category: 'Template',
    github: 'https://github.com/coccinella-labs/gitkeep',
    overview: 'Empty template repo with .gitkeep for meta purposes. The scaffolding is minimal, so the real work is yours.',
    installation: 'git clone https://github.com/coccinella-labs/gitkeep',
    license: 'MIT',
    status: 'Stable',
    related: [],
  },
  {
    name: 'glimpse',
    slug: 'glimpse',
    description: 'Logo symbols.',
    language: 'TypeScript',
    category: 'Template',
    github: 'https://github.com/coccinella-labs/glimpse',
    overview: 'Logo symbols. The scaffolding is minimal, so the real work is yours.',
    installation: 'git clone https://github.com/coccinella-labs/glimpse',
    license: 'Apache-2.0',
    status: 'Stable',
    related: [],
  },
  {
    name: 'go-kit',
    slug: 'go-kit',
    description: 'Build kit Go CLI foundation.',
    language: 'Go',
    category: 'Library',
    github: 'https://github.com/coccinella-labs/go-kit',
    overview: 'Build kit Go CLI foundation. It works on its own, without tying you down.',
    installation: 'go get github.com/coccinella-labs/go-kit@latest',
    license: 'MIT',
    status: 'Stable',
    related: [],
  },
  {
    name: 'gpucomm-bot',
    slug: 'gpucomm-bot',
    description: 'GPU-aware GitHub App + CI automation for gpucomm (webhooks, labeling, CUDA/PyTorch checks).',
    language: 'JavaScript',
    category: 'GitHub Action',
    github: 'https://github.com/coccinella-labs/gpucomm-bot',
    overview: 'GPU-aware GitHub App + CI automation for gpucomm (webhooks, labeling, CUDA/PyTorch checks). It slots into a workflow with a single use.',
    installation: '- uses: coccinella-labs/gpucomm-bot@main',
    license: 'MIT',
    status: 'Stable',
    related: [],
  },
  {
    name: 'gpucomm-fs',
    slug: 'gpucomm-fs',
    description: 'Binary-aware artifact store and filesystem foundation for gpucomm (GPU artifacts, datasets, weights).',
    language: 'Rust',
    category: 'Library',
    github: 'https://github.com/coccinella-labs/gpucomm-fs',
    overview: 'Binary-aware artifact store and filesystem foundation for gpucomm (GPU artifacts, datasets, weights). It works on its own, without tying you down.',
    installation: 'cargo install --git https://github.com/coccinella-labs/gpucomm-fs',
    license: 'MIT',
    status: 'Stable',
    related: [],
  },
  {
    name: 'harper',
    slug: 'harper',
    description: 'Rust agent runtime with a TUI, an HTTP API, and a sandbox.',
    language: 'Rust',
    category: 'CLI',
    github: 'https://github.com/coccinella-labs/harper',
    overview: 'Rust agent runtime with a TUI, an HTTP API, and a sandbox. It stays small enough to read and replace.',
    installation: 'cargo install --git https://github.com/coccinella-labs/harper',
    license: 'MIT',
    status: 'Stable',
    related: [],
  },
  {
    name: 'harper-notes',
    slug: 'harper-notes',
    description: 'Harper notes.',
    language: 'Rust',
    category: 'Experiment',
    github: 'https://github.com/coccinella-labs/harper-notes',
    overview: 'Harper notes. Expect rough edges while its shape is being tested.',
    installation: 'cargo install --git https://github.com/coccinella-labs/harper-notes',
    license: 'Apache-2.0',
    status: 'Experimental',
    related: [],
  },
  {
    name: 'harperbot',
    slug: 'harperbot',
    description: 'GitHub App bot.',
    language: 'Python',
    category: 'GitHub Action',
    github: 'https://github.com/coccinella-labs/harperbot',
    overview: 'GitHub App bot. It slots into a workflow with a single use.',
    installation: '- uses: coccinella-labs/harperbot@main',
    license: 'MIT',
    status: 'Stable',
    related: [],
  },
  {
    name: 'harpertoken',
    slug: 'harpertoken',
    description: 'Fine tuning notes.',
    language: 'Python',
    category: 'Experiment',
    github: 'https://github.com/coccinella-labs/harpertoken',
    overview: 'Fine tuning notes. Expect rough edges while its shape is being tested.',
    installation: 'pip install git+https://github.com/coccinella-labs/harpertoken',
    license: 'MIT',
    status: 'Experimental',
    related: [],
  },
  {
    name: 'hautofix',
    slug: 'hautofix',
    description: 'Code repair tool.',
    language: 'TypeScript',
    category: 'CLI',
    github: 'https://github.com/coccinella-labs/hautofix',
    overview: 'Code repair tool. It stays small enough to read and replace.',
    installation: 'git clone https://github.com/coccinella-labs/hautofix',
    license: 'MIT',
    status: 'Stable',
    related: [],
  },
  {
    name: 'hbadges',
    slug: 'hbadges',
    description: 'Badge assets.',
    language: 'Python',
    category: 'Template',
    github: 'https://github.com/coccinella-labs/hbadges',
    overview: 'Badge assets. The scaffolding is minimal, so the real work is yours.',
    installation: 'pip install git+https://github.com/coccinella-labs/hbadges',
    license: 'MIT',
    status: 'Stable',
    related: [],
  },
  {
    name: 'hbotest',
    slug: 'hbotest',
    description: 'Webhook test.',
    language: 'Python',
    category: 'Experiment',
    github: 'https://github.com/coccinella-labs/hbotest',
    overview: 'Webhook test. Expect rough edges while its shape is being tested.',
    installation: 'pip install git+https://github.com/coccinella-labs/hbotest',
    license: 'MIT',
    status: 'Experimental',
    related: [],
  },
  {
    name: 'hello',
    slug: 'hello',
    description: 'React app.',
    language: 'JavaScript',
    category: 'Experiment',
    github: 'https://github.com/coccinella-labs/hello',
    overview: 'React app. Expect rough edges while its shape is being tested.',
    installation: 'git clone https://github.com/coccinella-labs/hello',
    license: 'MIT',
    status: 'Experimental',
    related: [],
  },
  {
    name: 'hi',
    slug: 'hi',
    description: 'Instrument hub.',
    language: 'Python',
    category: 'CLI',
    github: 'https://github.com/coccinella-labs/hi',
    overview: 'Instrument hub. It stays small enough to read and replace.',
    installation: 'pip install git+https://github.com/coccinella-labs/hi',
    license: 'Apache-2.0',
    status: 'Stable',
    related: [],
  },
  {
    name: 'homebrew-kit',
    slug: 'homebrew-kit',
    description: 'Distribution artifact.',
    language: 'Ruby',
    category: 'Library',
    github: 'https://github.com/coccinella-labs/homebrew-kit',
    overview: 'Distribution artifact. It works on its own, without tying you down.',
    installation: 'git clone https://github.com/coccinella-labs/homebrew-kit',
    license: 'MIT',
    status: 'Stable',
    related: [],
  },
  {
    name: 'homebrew-tap',
    slug: 'homebrew-tap',
    description: 'Homebrew formulas for Coccinella Labs projects.',
    language: 'Ruby',
    category: 'Library',
    github: 'https://github.com/coccinella-labs/homebrew-tap',
    overview: 'Homebrew formulas for Coccinella Labs projects. It works on its own, without tying you down.',
    installation: 'git clone https://github.com/coccinella-labs/homebrew-tap',
    license: 'MIT',
    status: 'Stable',
    related: [],
  },
  {
    name: 'hub',
    slug: 'hub',
    description: 'Central hub - connects all repos.',
    language: 'Shell',
    category: 'CLI',
    github: 'https://github.com/coccinella-labs/hub',
    overview: 'Central hub - connects all repos. It stays small enough to read and replace.',
    installation: 'git clone https://github.com/coccinella-labs/hub',
    license: 'MIT',
    status: 'Stable',
    related: [],
  },
  {
    name: 'hwhcore',
    slug: 'hwhcore',
    description: 'Constraint core.',
    language: 'Lean',
    category: 'Library',
    github: 'https://github.com/coccinella-labs/hwhcore',
    overview: 'Constraint core. It works on its own, without tying you down.',
    installation: 'git clone https://github.com/coccinella-labs/hwhcore',
    license: 'MIT',
    status: 'Stable',
    related: [],
  },
  {
    name: 'json-repo',
    slug: 'json-repo',
    description: 'Complete JSON schemas and templates repository.',
    language: 'JSON',
    category: 'Template',
    github: 'https://github.com/coccinella-labs/json-repo',
    overview: 'Complete JSON schemas and templates repository. The scaffolding is minimal, so the real work is yours.',
    installation: 'git clone https://github.com/coccinella-labs/json-repo',
    license: 'MIT',
    status: 'Stable',
    related: [],
  },
  {
    name: 'jupyterml',
    slug: 'jupyterml',
    description: 'Notebook ML agent.',
    language: 'Python',
    category: 'Experiment',
    github: 'https://github.com/coccinella-labs/jupyterml',
    overview: 'Notebook ML agent. Expect rough edges while its shape is being tested.',
    installation: 'pip install git+https://github.com/coccinella-labs/jupyterml',
    license: 'MIT',
    status: 'Experimental',
    related: [],
  },
  {
    name: 'kernelgo',
    slug: 'kernelgo',
    description: 'Kernel info CLI.',
    language: 'Shell',
    category: 'CLI',
    github: 'https://github.com/coccinella-labs/kernelgo',
    overview: 'Kernel info CLI. It stays small enough to read and replace.',
    installation: 'git clone https://github.com/coccinella-labs/kernelgo',
    license: 'MIT',
    status: 'Stable',
    related: [],
  },
  {
    name: 'kerneljs',
    slug: 'kerneljs',
    description: 'Kernel version CLI.',
    language: 'Shell',
    category: 'CLI',
    github: 'https://github.com/coccinella-labs/kerneljs',
    overview: 'Kernel version CLI. It stays small enough to read and replace.',
    installation: 'git clone https://github.com/coccinella-labs/kerneljs',
    license: 'MIT',
    status: 'Stable',
    related: [],
  },
  {
    name: 'kernels',
    slug: 'kernels',
    description: 'Swift GPU kernels.',
    language: 'Swift',
    category: 'Library',
    github: 'https://github.com/coccinella-labs/kernels',
    overview: 'Swift GPU kernels. It works on its own, without tying you down.',
    installation: 'git clone https://github.com/coccinella-labs/kernels',
    license: 'MIT',
    status: 'Stable',
    related: [],
  },
  {
    name: 'kernelswift',
    slug: 'kernelswift',
    description: 'Kernel info CLI.',
    language: 'Swift',
    category: 'CLI',
    github: 'https://github.com/coccinella-labs/kernelswift',
    overview: 'Kernel info CLI. It stays small enough to read and replace.',
    installation: 'git clone https://github.com/coccinella-labs/kernelswift',
    license: 'MIT',
    status: 'Stable',
    related: [],
  },
  {
    name: 'l2',
    slug: 'l2',
    description: 'Layer 2 notes.',
    language: 'Ruby',
    category: 'Experiment',
    github: 'https://github.com/coccinella-labs/l2',
    overview: 'Layer 2 notes. Expect rough edges while its shape is being tested.',
    installation: 'git clone https://github.com/coccinella-labs/l2',
    license: 'MIT',
    status: 'Experimental',
    related: [],
  },
  {
    name: 'latexgen',
    slug: 'latexgen',
    description: 'LaTeX generator.',
    language: 'Python',
    category: 'CLI',
    github: 'https://github.com/coccinella-labs/latexgen',
    overview: 'LaTeX generator. It stays small enough to read and replace.',
    installation: 'pip install git+https://github.com/coccinella-labs/latexgen',
    license: 'MIT',
    status: 'Stable',
    related: [],
  },
  {
    name: 'license',
    slug: 'license',
    description: 'Shared licenses and legal documents for all repositories.',
    language: 'Markdown',
    category: 'Template',
    github: 'https://github.com/coccinella-labs/license',
    overview: 'Shared licenses and legal documents for all repositories. The scaffolding is minimal, so the real work is yours.',
    installation: 'git clone https://github.com/coccinella-labs/license',
    license: 'MIT',
    status: 'Stable',
    related: [],
  },
  {
    name: 'lifeboat',
    slug: 'lifeboat',
    description: 'Kaggle dataset notes.',
    language: 'Jupyter Notebook',
    category: 'Experiment',
    github: 'https://github.com/coccinella-labs/lifeboat',
    overview: 'Kaggle dataset notes. Expect rough edges while its shape is being tested.',
    installation: 'git clone https://github.com/coccinella-labs/lifeboat',
    license: 'MIT',
    status: 'Experimental',
    related: [],
  },
  {
    name: 'lilt',
    slug: 'lilt',
    description: 'Android messenger.',
    language: 'Kotlin',
    category: 'Experiment',
    github: 'https://github.com/coccinella-labs/lilt',
    overview: 'Android messenger. Expect rough edges while its shape is being tested.',
    installation: 'git clone https://github.com/coccinella-labs/lilt',
    license: 'Apache-2.0',
    status: 'Experimental',
    related: [],
  },
  {
    name: 'loom',
    slug: 'loom',
    description: 'CI notes.',
    language: 'TypeScript',
    category: 'Experiment',
    github: 'https://github.com/coccinella-labs/loom',
    overview: 'CI notes. Expect rough edges while its shape is being tested.',
    installation: 'git clone https://github.com/coccinella-labs/loom',
    license: 'MIT',
    status: 'Experimental',
    related: [],
  },
  {
    name: 'macoskernel',
    slug: 'macoskernel',
    description: 'XNU build notes.',
    language: 'C',
    category: 'Experiment',
    github: 'https://github.com/coccinella-labs/macoskernel',
    overview: 'XNU build notes. Expect rough edges while its shape is being tested.',
    installation: 'git clone https://github.com/coccinella-labs/macoskernel',
    license: 'MIT',
    status: 'Experimental',
    related: [],
  },
  {
    name: 'manager',
    slug: 'manager',
    description: 'Recipe runner.',
    language: 'Python',
    category: 'CLI',
    github: 'https://github.com/coccinella-labs/manager',
    overview: 'Recipe runner. It stays small enough to read and replace.',
    installation: 'pip install git+https://github.com/coccinella-labs/manager',
    license: 'MIT',
    status: 'Stable',
    related: [],
  },
  {
    name: 'markdownpro',
    slug: 'markdownpro',
    description: 'Markdown workflow app.',
    language: 'TypeScript',
    category: 'Experiment',
    github: 'https://github.com/coccinella-labs/markdownpro',
    overview: 'Markdown workflow app. Expect rough edges while its shape is being tested.',
    installation: 'git clone https://github.com/coccinella-labs/markdownpro',
    license: 'MIT',
    status: 'Experimental',
    related: [],
  },
  {
    name: 'mcporg',
    slug: 'mcporg',
    description: 'GitHub org mapping.',
    language: 'Swift',
    category: 'CLI',
    github: 'https://github.com/coccinella-labs/mcporg',
    overview: 'GitHub org mapping. It stays small enough to read and replace.',
    installation: 'git clone https://github.com/coccinella-labs/mcporg',
    license: 'MIT',
    status: 'Stable',
    related: [],
  },
  {
    name: 'md',
    slug: 'md',
    description: 'Markdown formatting.',
    language: 'Markdown',
    category: 'CLI',
    github: 'https://github.com/coccinella-labs/md',
    overview: 'Markdown formatting. It stays small enough to read and replace.',
    installation: 'git clone https://github.com/coccinella-labs/md',
    license: 'MIT',
    status: 'Stable',
    related: [],
  },
  {
    name: 'memoraxx',
    slug: 'memoraxx',
    description: 'Llama terminal client.',
    language: 'C++',
    category: 'CLI',
    github: 'https://github.com/coccinella-labs/memoraxx',
    overview: 'Llama terminal client. It stays small enough to read and replace.',
    installation: 'git clone https://github.com/coccinella-labs/memoraxx',
    license: 'Apache-2.0',
    status: 'Stable',
    related: [],
  },
  {
    name: 'metal',
    slug: 'metal',
    description: 'Swift package notes.',
    language: 'Swift',
    category: 'Experiment',
    github: 'https://github.com/coccinella-labs/metal',
    overview: 'Swift package notes. Expect rough edges while its shape is being tested.',
    installation: 'git clone https://github.com/coccinella-labs/metal',
    license: 'MIT',
    status: 'Experimental',
    related: [],
  },
  {
    name: 'ml',
    slug: 'ml',
    description: 'Machine learning framework.',
    language: 'C++',
    category: 'Library',
    github: 'https://github.com/coccinella-labs/ml',
    overview: 'Machine learning framework. It works on its own, without tying you down.',
    installation: 'git clone https://github.com/coccinella-labs/ml',
    license: 'Apache-2.0',
    status: 'Stable',
    related: [],
  },
  {
    name: 'mlapi',
    slug: 'mlapi',
    description: 'Machine learning API.',
    language: 'Python',
    category: 'Library',
    github: 'https://github.com/coccinella-labs/mlapi',
    overview: 'Machine learning API. It works on its own, without tying you down.',
    installation: 'pip install git+https://github.com/coccinella-labs/mlapi',
    license: 'MIT',
    status: 'Stable',
    related: [],
  },
  {
    name: 'mlxlm',
    slug: 'mlxlm',
    description: 'M1 inference tests.',
    language: 'Python',
    category: 'Experiment',
    github: 'https://github.com/coccinella-labs/mlxlm',
    overview: 'M1 inference tests. Expect rough edges while its shape is being tested.',
    installation: 'pip install git+https://github.com/coccinella-labs/mlxlm',
    license: 'MIT',
    status: 'Experimental',
    related: [],
  },
  {
    name: 'mnistcnn',
    slug: 'mnistcnn',
    description: 'Digit classifier.',
    language: 'Python',
    category: 'Experiment',
    github: 'https://github.com/coccinella-labs/mnistcnn',
    overview: 'Digit classifier. Expect rough edges while its shape is being tested.',
    installation: 'pip install git+https://github.com/coccinella-labs/mnistcnn',
    license: 'MIT',
    status: 'Experimental',
    related: [],
  },
  {
    name: 'models',
    slug: 'models',
    description: 'Model notes.',
    language: 'Python',
    category: 'Experiment',
    github: 'https://github.com/coccinella-labs/models',
    overview: 'Model notes. Expect rough edges while its shape is being tested.',
    installation: 'pip install git+https://github.com/coccinella-labs/models',
    license: 'MIT',
    status: 'Experimental',
    related: [],
  },
  {
    name: 'molplatform',
    slug: 'molplatform',
    description: 'Computer science service.',
    language: 'Python',
    category: 'Experiment',
    github: 'https://github.com/coccinella-labs/molplatform',
    overview: 'Computer science service. Expect rough edges while its shape is being tested.',
    installation: 'pip install git+https://github.com/coccinella-labs/molplatform',
    license: 'MIT',
    status: 'Experimental',
    related: [],
  },
  {
    name: 'omnitype',
    slug: 'omnitype',
    description: 'Type checker.',
    language: 'Rust',
    category: 'CLI',
    github: 'https://github.com/coccinella-labs/omnitype',
    overview: 'Type checker. It stays small enough to read and replace.',
    installation: 'cargo install --git https://github.com/coccinella-labs/omnitype',
    license: 'MIT',
    status: 'Stable',
    related: [],
  },
  {
    name: 'organictyping',
    slug: 'organictyping',
    description: 'Keystroke dynamics analyzer.',
    language: 'TypeScript',
    category: 'CLI',
    github: 'https://github.com/coccinella-labs/organictyping',
    overview: 'Keystroke dynamics analyzer. It stays small enough to read and replace.',
    installation: 'git clone https://github.com/coccinella-labs/organictyping',
    license: 'MIT',
    status: 'Stable',
    related: [],
  },
  {
    name: 'palmshed',
    slug: 'palmshed',
    description: 'Personal site and notes in TypeScript.',
    language: 'TypeScript',
    category: 'Experiment',
    github: 'https://github.com/coccinella-labs/palmshed',
    overview: 'Personal site and notes in TypeScript. Expect rough edges while its shape is being tested.',
    installation: 'git clone https://github.com/coccinella-labs/palmshed',
    license: 'MIT',
    status: 'Experimental',
    related: [],
  },
  {
    name: 'palmshed-org',
    slug: 'palmshed-org',
    description: 'Org profile.',
    language: 'Markdown',
    category: 'Template',
    github: 'https://github.com/coccinella-labs/palmshed-org',
    overview: 'Org profile. The scaffolding is minimal, so the real work is yours.',
    installation: 'git clone https://github.com/coccinella-labs/palmshed-org',
    license: 'MIT',
    status: 'Stable',
    related: [],
  },
  {
    name: 'patchcore',
    slug: 'patchcore',
    description: 'Anomaly detection model.',
    language: 'Jupyter Notebook',
    category: 'Experiment',
    github: 'https://github.com/coccinella-labs/patchcore',
    overview: 'Anomaly detection model. Expect rough edges while its shape is being tested.',
    installation: 'git clone https://github.com/coccinella-labs/patchcore',
    license: 'MIT',
    status: 'Experimental',
    related: [],
  },
  {
    name: 'path',
    slug: 'path',
    description: 'Navigation notes.',
    language: 'HTML',
    category: 'Experiment',
    github: 'https://github.com/coccinella-labs/path',
    overview: 'Navigation notes. Expect rough edges while its shape is being tested.',
    installation: 'git clone https://github.com/coccinella-labs/path',
    license: 'MIT',
    status: 'Experimental',
    related: [],
  },
  {
    name: 'pathutils',
    slug: 'pathutils',
    description: 'Path utilities.',
    language: 'TypeScript',
    category: 'Library',
    github: 'https://github.com/coccinella-labs/pathutils',
    overview: 'Path utilities. It works on its own, without tying you down.',
    installation: 'npm install github:coccinella-labs/pathutils',
    license: 'MIT',
    status: 'Stable',
    related: [],
  },
  {
    name: 'press',
    slug: 'press',
    description: 'A bookshelf of Christian books.',
    language: 'TypeScript',
    category: 'Experiment',
    github: 'https://github.com/coccinella-labs/press',
    overview: 'A bookshelf of Christian books. Expect rough edges while its shape is being tested.',
    installation: 'git clone https://github.com/coccinella-labs/press',
    license: 'MIT',
    status: 'Experimental',
    related: [],
  },
  {
    name: 'proof',
    slug: 'proof',
    description: 'Deterministic PR body review.',
    language: 'YAML',
    category: 'GitHub Action',
    github: 'https://github.com/coccinella-labs/proof',
    overview: 'Checks PR title format, required sections, body word count, issue links, and file:line anchors with no model and no API keys beyond the GitHub token. It slots into a workflow with a single use.',
    installation: '- uses: coccinella-labs/proof@v1',
    license: 'MIT',
    status: 'Stable',
    related: ['second'],
  },
  {
    name: 'prtemplate',
    slug: 'prtemplate',
    description: 'Pull request template.',
    language: 'YAML',
    category: 'Template',
    github: 'https://github.com/coccinella-labs/prtemplate',
    overview: 'Pull request template. The scaffolding is minimal, so the real work is yours.',
    installation: 'git clone https://github.com/coccinella-labs/prtemplate',
    license: 'MIT',
    status: 'Stable',
    related: [],
  },
  {
    name: 'rag',
    slug: 'rag',
    description: 'Containerized Python package.',
    language: 'Python',
    category: 'Library',
    github: 'https://github.com/coccinella-labs/rag',
    overview: 'Containerized Python package. It works on its own, without tying you down.',
    installation: 'pip install git+https://github.com/coccinella-labs/rag',
    license: 'MIT',
    status: 'Stable',
    related: [],
  },
  {
    name: 'react-template',
    slug: 'react-template',
    description: 'React UI template with Vite, TypeScript, Tailwind CSS.',
    language: 'TypeScript',
    category: 'Template',
    github: 'https://github.com/coccinella-labs/react-template',
    overview: 'React UI template with Vite, TypeScript, Tailwind CSS. The scaffolding is minimal, so the real work is yours.',
    installation: 'git clone https://github.com/coccinella-labs/react-template',
    license: 'MIT',
    status: 'Stable',
    related: [],
  },
  {
    name: 'resume',
    slug: 'resume',
    description: 'resume builder.',
    language: 'TypeScript',
    category: 'CLI',
    github: 'https://github.com/coccinella-labs/resume',
    overview: 'resume builder. It stays small enough to read and replace.',
    installation: 'git clone https://github.com/coccinella-labs/resume',
    license: 'MIT',
    status: 'Stable',
    related: [],
  },
  {
    name: 'rl',
    slug: 'rl',
    description: 'Reinforcement learning framework.',
    language: 'Python',
    category: 'Library',
    github: 'https://github.com/coccinella-labs/rl',
    overview: 'Reinforcement learning framework. It works on its own, without tying you down.',
    installation: 'pip install git+https://github.com/coccinella-labs/rl',
    license: 'MIT',
    status: 'Stable',
    related: [],
  },
  {
    name: 'scout',
    slug: 'scout',
    description: 'Storage tool.',
    language: 'Swift',
    category: 'CLI',
    github: 'https://github.com/coccinella-labs/scout',
    overview: 'Storage tool. It stays small enough to read and replace.',
    installation: 'git clone https://github.com/coccinella-labs/scout',
    license: 'MIT',
    status: 'Stable',
    related: [],
  },
  {
    name: 'second',
    slug: 'second',
    description: 'Model-backed inline PR review.',
    language: 'YAML',
    category: 'GitHub Action',
    github: 'https://github.com/coccinella-labs/second',
    overview: 'A second pair of eyes on the diff using OpenRouter free quota: comments only on real defects, silent otherwise. It slots into a workflow with a single use.',
    installation: '- uses: coccinella-labs/second@v1',
    license: 'MIT',
    status: 'Experimental',
    related: ['proof'],
  },
  {
    name: 'simengine',
    slug: 'simengine',
    description: 'Physics simulation engine.',
    language: 'Makefile',
    category: 'Library',
    github: 'https://github.com/coccinella-labs/simengine',
    overview: 'Physics simulation engine. It works on its own, without tying you down.',
    installation: 'git clone https://github.com/coccinella-labs/simengine',
    license: 'MIT',
    status: 'Stable',
    related: [],
  },
  {
    name: 'skills',
    slug: 'skills',
    description: 'Skills and capabilities for agents and CLI.',
    language: 'Markdown',
    category: 'Template',
    github: 'https://github.com/coccinella-labs/skills',
    overview: 'Skills and capabilities for agents and CLI. The scaffolding is minimal, so the real work is yours.',
    installation: 'git clone https://github.com/coccinella-labs/skills',
    license: 'MIT',
    status: 'Stable',
    related: [],
  },
  {
    name: 'stillness',
    slug: 'stillness',
    description: 'Minimal page theme.',
    language: 'HTML',
    category: 'Template',
    github: 'https://github.com/coccinella-labs/stillness',
    overview: 'Minimal page theme. The scaffolding is minimal, so the real work is yours.',
    installation: 'git clone https://github.com/coccinella-labs/stillness',
    license: 'MIT',
    status: 'Stable',
    related: [],
  },
  {
    name: 'stremiodiag',
    slug: 'stremiodiag',
    description: 'Stremio signing diagnostics.',
    language: 'Shell',
    category: 'CLI',
    github: 'https://github.com/coccinella-labs/stremiodiag',
    overview: 'Stremio signing diagnostics. It stays small enough to read and replace.',
    installation: 'git clone https://github.com/coccinella-labs/stremiodiag',
    license: 'MIT',
    status: 'Stable',
    related: [],
  },
  {
    name: 'surface',
    slug: 'surface',
    description: 'GitHub surface audit.',
    language: 'Shell',
    category: 'CLI',
    github: 'https://github.com/coccinella-labs/surface',
    overview: 'GitHub surface audit. It stays small enough to read and replace.',
    installation: 'git clone https://github.com/coccinella-labs/surface',
    license: 'MIT',
    status: 'Stable',
    related: [],
  },
  {
    name: 'swe-agent',
    slug: 'swe-agent',
    description: 'SWE Agent template and utilities.',
    language: 'Python',
    category: 'Template',
    github: 'https://github.com/coccinella-labs/swe-agent',
    overview: 'SWE Agent template and utilities. The scaffolding is minimal, so the real work is yours.',
    installation: 'pip install git+https://github.com/coccinella-labs/swe-agent',
    license: 'MIT',
    status: 'Stable',
    related: [],
  },
  {
    name: 'theme',
    slug: 'theme',
    description: 'Minimal theme.',
    language: 'Shell',
    category: 'Template',
    github: 'https://github.com/coccinella-labs/theme',
    overview: 'Minimal theme. The scaffolding is minimal, so the real work is yours.',
    installation: 'git clone https://github.com/coccinella-labs/theme',
    license: 'MIT',
    status: 'Stable',
    related: [],
  },
  {
    name: 'thread',
    slug: 'thread',
    description: 'Tiled image pipeline.',
    language: 'C++',
    category: 'Library',
    github: 'https://github.com/coccinella-labs/thread',
    overview: 'Tiled image pipeline. It works on its own, without tying you down.',
    installation: 'git clone https://github.com/coccinella-labs/thread',
    license: 'BSD-3-Clause',
    status: 'Stable',
    related: [],
  },
  {
    name: 'tokensdk',
    slug: 'tokensdk',
    description: 'Harpertoken SDK.',
    language: 'TypeScript',
    category: 'Library',
    github: 'https://github.com/coccinella-labs/tokensdk',
    overview: 'Harpertoken SDK. It works on its own, without tying you down.',
    installation: 'npm install github:coccinella-labs/tokensdk',
    license: 'Apache-2.0',
    status: 'Stable',
    related: [],
  },
  {
    name: 'tracking',
    slug: 'tracking',
    description: 'Activity workflow.',
    language: 'YAML',
    category: 'GitHub Action',
    github: 'https://github.com/coccinella-labs/tracking',
    overview: 'Activity workflow. It slots into a workflow with a single use.',
    installation: '- uses: coccinella-labs/tracking@main',
    license: 'MIT',
    status: 'Stable',
    related: [],
  },
  {
    name: 'tts',
    slug: 'tts',
    description: 'Text to speech.',
    language: 'TypeScript',
    category: 'CLI',
    github: 'https://github.com/coccinella-labs/tts',
    overview: 'Text to speech. It stays small enough to read and replace.',
    installation: 'git clone https://github.com/coccinella-labs/tts',
    license: 'Apache-2.0',
    status: 'Stable',
    related: [],
  },
  {
    name: 'userstring',
    slug: 'userstring',
    description: 'User string generator.',
    language: 'Python',
    category: 'CLI',
    github: 'https://github.com/coccinella-labs/userstring',
    overview: 'User string generator. It stays small enough to read and replace.',
    installation: 'pip install git+https://github.com/coccinella-labs/userstring',
    license: 'MIT',
    status: 'Stable',
    related: [],
  },
  {
    name: 'vertex',
    slug: 'vertex',
    description: 'Understand software before you change it.',
    language: 'TypeScript',
    category: 'CLI',
    github: 'https://github.com/coccinella-labs/vertex',
    overview: 'Understand software before you change it. It stays small enough to read and replace.',
    installation: 'git clone https://github.com/coccinella-labs/vertex',
    license: 'MIT',
    status: 'Stable',
    related: [],
  },
  {
    name: 'vesper',
    slug: 'vesper',
    description: 'Gemini client.',
    language: 'Python',
    category: 'CLI',
    github: 'https://github.com/coccinella-labs/vesper',
    overview: 'Gemini client. It stays small enough to read and replace.',
    installation: 'pip install git+https://github.com/coccinella-labs/vesper',
    license: 'MIT',
    status: 'Stable',
    related: [],
  },
  {
    name: 'videos',
    slug: 'videos',
    description: 'Video notes.',
    language: 'Python',
    category: 'Experiment',
    github: 'https://github.com/coccinella-labs/videos',
    overview: 'Video notes. Expect rough edges while its shape is being tested.',
    installation: 'pip install git+https://github.com/coccinella-labs/videos',
    license: 'MIT',
    status: 'Experimental',
    related: [],
  },
  {
    name: 'vision',
    slug: 'vision',
    description: 'Vision demo.',
    language: 'JavaScript',
    category: 'Experiment',
    github: 'https://github.com/coccinella-labs/vision',
    overview: 'Vision demo. Expect rough edges while its shape is being tested.',
    installation: 'git clone https://github.com/coccinella-labs/vision',
    license: 'MIT',
    status: 'Experimental',
    related: [],
  },
  {
    name: 'warnings',
    slug: 'warnings',
    description: 'Warning and alert messages repository for slash commands.',
    language: 'YAML',
    category: 'GitHub Action',
    github: 'https://github.com/coccinella-labs/warnings',
    overview: 'Warning and alert messages repository for slash commands. It slots into a workflow with a single use.',
    installation: '- uses: coccinella-labs/warnings@main',
    license: 'MIT',
    status: 'Stable',
    related: [],
  },
  {
    name: 'weight',
    slug: 'weight',
    description: 'Message classifier.',
    language: 'Dart',
    category: 'Experiment',
    github: 'https://github.com/coccinella-labs/weight',
    overview: 'Message classifier. Expect rough edges while its shape is being tested.',
    installation: 'git clone https://github.com/coccinella-labs/weight',
    license: 'MIT',
    status: 'Experimental',
    related: [],
  },
  {
    name: 'welcomebot',
    slug: 'welcomebot',
    description: 'Welcome bot.',
    language: 'JavaScript',
    category: 'GitHub Action',
    github: 'https://github.com/coccinella-labs/welcomebot',
    overview: 'Welcome bot. It slots into a workflow with a single use.',
    installation: '- uses: coccinella-labs/welcomebot@main',
    license: 'MIT',
    status: 'Stable',
    related: [],
  },
  {
    name: 'welcomeissues',
    slug: 'welcomeissues',
    description: 'Welcome issues.',
    language: 'YAML',
    category: 'GitHub Action',
    github: 'https://github.com/coccinella-labs/welcomeissues',
    overview: 'Welcome issues. It slots into a workflow with a single use.',
    installation: '- uses: coccinella-labs/welcomeissues@main',
    license: 'MIT',
    status: 'Stable',
    related: [],
  },
  {
    name: 'xgboostapi',
    slug: 'xgboostapi',
    description: 'Prediction API.',
    language: 'Python',
    category: 'Library',
    github: 'https://github.com/coccinella-labs/xgboostapi',
    overview: 'Prediction API. It works on its own, without tying you down.',
    installation: 'pip install git+https://github.com/coccinella-labs/xgboostapi',
    license: 'MIT',
    status: 'Stable',
    related: [],
  },
  {
    name: 'xnubuild',
    slug: 'xnubuild',
    description: 'XNU build notes.',
    language: 'Shell',
    category: 'Experiment',
    github: 'https://github.com/coccinella-labs/xnubuild',
    overview: 'XNU build notes. Expect rough edges while its shape is being tested.',
    installation: 'git clone https://github.com/coccinella-labs/xnubuild',
    license: 'MIT',
    status: 'Experimental',
    related: [],
  },]

export type Release = {
  version: string
  slug: string
}

export const releases: Release[] = [
  { version: "v0.1.0", slug: "clipb" },
  { version: "v0.1.0", slug: "craft" },
  { version: "v0.1.0", slug: "dotenv-keep" },
  { version: "v0.1.0", slug: "fmtcheck" },
  { version: "v0.1.0", slug: "gh-tag" },
  { version: "v0.1.0", slug: "mini" },
  { version: "v0.1.0", slug: "release-notes" },
  { version: "v0.1.0", slug: "startkit" },
  { version: "v0.1.0", slug: "bump" },
  { version: "v0.1.0", slug: "echo" },
  { version: "v0.1.0", slug: "gon" },
  { version: "v0.1.0", slug: "nightly" },
  { version: "v0.1.0", slug: "release-assets" },
  { version: "v0.1.0", slug: "rust-nightly" },
  { version: "v1", slug: "auto-merge" },
  { version: "v1", slug: "bot" },
  { version: "v1", slug: "cancel" },
  { version: "v1", slug: "lock" },
  { version: "v1", slug: "prune" },
  { version: "v1", slug: "proof" },
  { version: "v1", slug: "rust-fix" },
  { version: "v1", slug: "second" },
  { version: "v1", slug: "stale" },
  { version: "v1", slug: "title" },
  { version: "v1.0.0", slug: "activity" },
  { version: "v1.0.0", slug: "release" },
  { version: "v2", slug: "auto-label" },
]

export type Activity = {
  label: string
  slug: string
}

export const recentlyUpdated: Activity[] = [
  { label: "Recent", slug: "clipb" },
  { label: "Recent", slug: "craft" },
  { label: "Recent", slug: "dotenv-keep" },
  { label: "Recent", slug: "fmtcheck" },
  { label: "Recent", slug: "gh-tag" },
  { label: "Recent", slug: "mini" },
  { label: "Recent", slug: "release-notes" },
  { label: "Recent", slug: "startkit" },
  { label: "Recent", slug: "bump" },
  { label: "Recent", slug: "echo" },
  { label: "Recent", slug: "gon" },
  { label: "Recent", slug: "nightly" },
  { label: "Recent", slug: "release-assets" },
  { label: "Recent", slug: "rust-nightly" },
  { label: "Recent", slug: "auto-merge" },
  { label: "Recent", slug: "bot" },
  { label: "Recent", slug: "cancel" },
  { label: "Recent", slug: "lock" },
  { label: "Recent", slug: "prune" },
  { label: "Recent", slug: "proof" },
  { label: "Recent", slug: "rust-fix" },
  { label: "Recent", slug: "second" },
  { label: "Recent", slug: "stale" },
  { label: "Recent", slug: "title" },
  { label: "Recent", slug: "activity" },
  { label: "Recent", slug: "release" },
  { label: "Recent", slug: "auto-label" },
]

export const philosophy = [
  {
    title: "Small over large",
    body: "A tool should be small enough to read, reason about, and replace.",
  },
  {
    title: "Stable over clever",
    body: "Predictable behavior beats impressive internals.",
  },
  {
    title: "Useful over busy",
    body: "Features earn their place by solving real problems.",
  },
  {
    title: "Independent by design",
    body: "Every project stands on its own. No lock-in, no scaffolding.",
  },
]

export const principles = [
  "solve one problem",
  "stay easy to understand",
  "have clear documentation",
  "remain independently useful",
]

export const searchFilters = {
  languages,
  categories: [
    "CLI",
    "GitHub Action",
    "Library",
    "Template",
    "Experiment",
  ] as Category[],
}