import type { App } from "./types"
import {
  HarperMockup,
  OrganicTypingMockup,
  MemoraxxMockup,
  HautofixMockup,
  BrowserMockup,
  VesperMockup,
  PressMockup,
  TokensdkMockup,
  OmnnitypeMockup,
  VertexMockup,
} from "./mockups"

export const apps: App[] = [
  {
    name: "organictyping",
    tag: "Keystroke analytics",
    glyph: "~",
    tint: "from-rose-500/70 to-amber-400/50",
    repo: "https://github.com/coccinella-labs/organictyping",
    source: "github",
    Mockup: OrganicTypingMockup,
  },
  {
    name: "memoraxx",
    tag: "Local LLM client",
    glyph: "▮",
    tint: "from-teal-500/70 to-emerald-400/50",
    repo: "https://github.com/coccinella-labs/memoraxx",
    source: "github",
    Mockup: MemoraxxMockup,
  },
  {
    name: "hautofix",
    tag: "AI text edit",
    glyph: "✎",
    tint: "from-indigo-500/70 to-sky-400/50",
    repo: "https://github.com/coccinella-labs/hautofix",
    source: "github",
    Mockup: HautofixMockup,
  },
  {
    name: "browser",
    tag: "Desktop browser",
    glyph: "◎",
    tint: "from-orange-500/70 to-rose-400/50",
    repo: "https://github.com/coccinella-labs/browser",
    source: "github",
    Mockup: BrowserMockup,
  },
  {
    name: "press",
    tag: "Bookshelf",
    glyph: "▤",
    tint: "from-sky-500/70 to-violet-400/50",
    repo: "https://github.com/coccinella-labs/press",
    source: "github",
    Mockup: PressMockup,
  },
  {
    name: "vesper",
    tag: "Gemini · PR review",
    glyph: "◇",
    tint: "from-fuchsia-500/70 to-pink-400/50",
    repo: "https://github.com/coccinella-labs/vesper",
    source: "github",
    Mockup: VesperMockup,
  },
  {
    name: "tokensdk",
    tag: "Harpertoken SDK",
    glyph: "◉",
    tint: "from-cyan-500/70 to-blue-400/50",
    repo: "https://github.com/coccinella-labs/tokensdk",
    source: "github",
    Mockup: TokensdkMockup,
  },
  {
    name: "omnitype",
    tag: "Rust type checker",
    glyph: "#",
    tint: "from-amber-500/70 to-yellow-400/50",
    repo: "https://github.com/coccinella-labs/omnitype",
    source: "github",
    Mockup: OmnnitypeMockup,
  },
  {
    name: "vertex",
    tag: "Repo insight",
    glyph: "⌗",
    tint: "from-violet-500/70 to-indigo-400/50",
    repo: "https://github.com/coccinella-labs/vertex",
    source: "github",
    Mockup: VertexMockup,
  },
  {
    name: "harpertoken",
    tag: "Models · Spaces · live",
    glyph: "♥",
    tint: "from-yellow-500/70 to-amber-400/50",
    repo: "https://huggingface.co/harpertoken",
    source: "hf",
  },
]

export const harperApp: App = {
  name: "harper",
  tag: "Agent harness",
  glyph: "◆",
  tint: "from-[#f34b7d] to-[#f34b7d]/40",
  repo: "https://github.com/coccinella-labs/harper",
  source: "github",
  Mockup: HarperMockup,
}

export const allApps: App[] = [harperApp, ...apps]
